insert into monument (id, country_code, country_name, city_name, latitude, longitude, monument_name, description, photo_url) values (1, 'ES', 'Spain', 'Seville', 37.3891, -5.9845, 'Giralda', 'A former minaret that was converted to a bell tower for the Seville Cathedral.', 'https://example.com/giralda.jpg');
insert into monument (id, country_code, country_name, city_name, latitude, longitude, monument_name, description, photo_url) values (2, 'ES', 'Spain', 'Seville', 37.3891, -5.9845, 'Alcazar', 'A royal palace in Seville, Spain, built for the Christian king Peter of Castile.', 'https://example.com/alcazar.jpg');
insert into monument (id, country_code, country_name, city_name, latitude, longitude, monument_name, description, photo_url) values (3, 'ES', 'Spain', 'Seville', 37.3891, -5.9845, 'Plaza de España', 'A plaza in the Parque de María Luisa, in Seville, Spain, built in 1928 for the Ibero-American Exposition of 1929.', 'https://example.com/plaza_de_espana.jpg');
insert into monument (id, country_code, country_name, city_name, latitude, longitude, monument_name, description, photo_url) values (4, 'ES', 'Spain', 'Seville', 37.3891, -5.9845, 'Metropol Parasol', 'A wooden structure located at La Encarnación square, in the old quarter of Seville, Spain.', 'https://example.com/metropol_parasol.jpg');
insert into monument (id, country_code, country_name, city_name, latitude, longitude, monument_name, description, photo_url) values (5, 'ES', 'Spain', 'Seville', 37.3891, -5.9845, 'Torre del Oro', 'A dodecagonal military watchtower in Seville, southern Spain.', 'https://example.com/torre_del_oro.jpg');
insert into monument (id, country_code, country_name, city_name, latitude, longitude, monument_name, description, photo_url) values (6, 'ES', 'Spain', 'Seville', 37.3891, -5.9845, 'Seville Cathedral', 'A Roman Catholic cathedral in Seville, Spain.', 'https://example.com/seville_cathedral.jpg');
insert into monument (id, country_code, country_name, city_name, latitude, longitude, monument_name, description, photo_url) values (7, 'ES', 'Spain', 'Ubeda', 38.0133, -3.3705, 'Juan Vazquez de Molina Palace', 'A Renaissance palace in Ubeda, Spain.', 'https://example.com/vazquez_de_molina_palace.jpg');

ALTER SEQUENCE monument_seq RESTART WITH 1000;
